site_name: KochiOrgBook Community Cloud
theme:
    name: material
markdown extensions:
    - attr_list    
nav:
    - Overview: overview.md
    - Dependent Projects: dependent.md
    - Motivation: motivation.md
    - Use Case Diagram: usecase.md
    - Status of the project: status.md
    - Solution: solution.md
    - Contributors: contributors.md
    - License: license.md